#!/bin/bash

#SBATCH -n 16
#SBATCH --nodes=1               # Attention: Only if multi-node machine
#SBATCH --ntasks-per-node 16
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --job-name=OpenFOAM_v10
#SBATCH --time=2-00:00:00

source ~/.bashrc

renumberMesh
setFields > setFieldsLog
decomposePar > decomposeParLog
mpirun -np 16 interFoam -parallel > interFoamLog

